### ISSUE TITLE
Compiler issue using Eigen Wrappers

### ISSUE THREAD

**Issue by kfavre** [kthohr/optim#33] opened 2021-02-15 16:38 UTC
Hello,

I happen to have the following issue when I try to compile the library using Eigen.
I have the same issue if I try to compile the header-only or the shared-library.

It looks like there is a mismatch with Eigen and optim.

I am using Eigen 3.3.4 version.

```
/home/user/project/src/../header_only_version/unconstrained/nm.hpp:202:69 error: no match for call to ‘(optim::Vec_t {aka Eigen::Matrix<double, -1, 1>}) (optim::VecInt_t&)’
         simplex_fn_vals = OPTIM_MATOPS_EVAL(simplex_fn_vals(sort_vec));

/home/user/project/src/../header_only_version/misc/matrix_ops/eval.hpp:30:35: note: in definition of macro ‘OPTIM_MATOPS_EVAL’
     #define OPTIM_MATOPS_EVAL(x) (x).eval()
                                   ^
In file included from /usr/include/eigen3/Eigen/Core:414:0,
                 from /usr/include/eigen3/Eigen/StdVector:14,
                 from /usr/include/pcl-1.8/pcl/point_cloud.h:46,
                 from /usr/include/pcl-1.8/pcl/io/pcd_io.h:43,
                 from /home/kfavre/git_repository/3d-vision/recalage/PCL/mutual_information/src/mutual_information.cpp:12:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:115:41: note: candidate: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index, Eigen::Index) const [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]
     EIGEN_STRONG_INLINE CoeffReturnType operator()(Index row, Index col) const


etc....


/home/user/project/src/../header_only_version/misc/matrix_ops/access.hpp:35:50: error: ‘all’ is not a member of ‘Eigen’
     #define OPTIM_MATOPS_ROWS(x, v) (x)(v,Eigen::all) // v is a vector
                                                  ^
/home/user/project/src/../header_only_version/misc/matrix_ops/eval.hpp:30:35: note: in definition of macro ‘OPTIM_MATOPS_EVAL’
     #define OPTIM_MATOPS_EVAL(x) (x).eval()
```

Here is the code that I want to execute (which is pretty simple):

```
#define OPTIM_ENABLE_EIGEN_WRAPPERS
#include "../header_only_version/optim.hpp"
  double ackley_fn(const Eigen::VectorXd& vals_inp, Eigen::VectorXd* grad_out, void* opt_data)
  {
      const double x = vals_inp(0);
      const double y = vals_inp(1);

      double obj_val = -20*std::exp( -0.2*std::sqrt(0.5*(x*x + y*y)) ) - std::exp( 0.5*(std::cos(2*M_PI*x) + std::cos(2*M_PI*y)) ) + 22.718282L;

      return obj_val;
  }

int main (int argc, char** argv)
{
// initial values:
		Eigen::VectorXd x = Eigen::VectorXd::Zero(2,1); // (2,2)
		x[0] = 1.3;
		x[1] = 1.4;

	    bool success = optim::de(x,ackley_fn,nullptr);
            std::cout << "\nde: solution to Ackley test:\n" << x << std::endl;
}

```

Do not hesitate to ask if I can give any more precisions.
Thank you in advance for your help!

**Comment by titovmaxim** [comment] 2021-02-16 02:44
Looks like duplicate of #29. Which -D options do you you for compilation? Please check if Eigen is properly included from optim_options.hpp under #ifdef OPTIM_ENABLE_EIGEN_WRAPPERS. Are you sure you have Eigen sources nearby?

**Comment by kfavre** [comment] 2021-02-16 14:52
I compile my code using the configure file with the option `-l eigen` which leads to -D option being `-DOPTIM_ENABLE_EIGEN_WRAPPERS` 
The path to Eigen library seems ok (I use Eigen in several other projects without trouble).
The includes in optim_options.hpp also seem fine.

**Comment by kfavre** [comment] 2021-02-17 09:35
Quick update:
it looks like the root cause of the problem is in the unconstrained/nm.cpp file (which displays the error in the console)
I could compile the optim lib properly, using eigen, by removing it. As I do not need the Nelder-Mead algorithm I did not look any further in the issue, so it is more of a walk around than a solution.
The tutorial example works fine.

**Comment by kthohr** [comment] 2021-02-20 18:06
My guess:

* you need to update your copy of Eigen,
* your include path for Eigen is not set correctly, and/or
* there is an issue with the compiler flags you are passing (which may or may not be related to the include path for Eigen). 

I cannot replicate the error when using the latest version of Eigen.

**Closed** 2021-03-13 21:08 UTC

**Comment by qacwnfq** [comment] 2021-03-23 14:08
Indeed this Error does not happen with a newer version of Eigen. (Issue happens with  3.3.7 but works with  3.4.99)

**Comment by ts826848** [comment] 2021-03-23 16:16
Can confirm tip-of-HEAD Eigen works.

Looks like `Eigen::all` was (is? will be?) [introduced in Eigen 3.4](https://eigen.tuxfamily.org/dox-devel/group__TutorialSlicingIndexing.html):

> # Slicing and Indexing
> This page presents the numerous possibilities offered by operator() to index sub-set of rows and columns. This API has been introduced in Eigen 3.4.
> ...
> The symbol `Eigen::all` representing the whole set of respective rows or columns in increasing order.

Interestingly, the docs were [committed 2018-11-09](https://gitlab.com/libeigen/eigen/-/commit/d7c644213cbf548f67aeb7ed6f872aef96c1dbd2), and the [change moving `Eigen::placeholders::all` to `Eigen::all`](2014c7ae28c592063f6887632682231ed862cfc5) was committed 2018-09-15, so seems this has been baking for quite a while.
